### PR TITLE
Adjust the call paramters for the seekpath_structure_analysis function accordingly.

### PR DESCRIPTION
**Pull request by hongyi-zhao**
See https://github.com/aiidateam/aiida-wannier90-workflows/issues/3
and
https://github.com/aiidateam/aiida-quantumespresso/commit/ec24908162fe9c606bd6e491d6253f31e2436957

 `seekpath_structure_analysis`: expand parameter input into keywords
    
So, adjust the call method for the seekpath_structure_analysis function accordingly.

### CODE REVIEW

**Comment by sphuber** [comment]
I am not sure if you guys actually tested this, but I think this won't work. The `seekpath_parameters` is a `Dict` node, but just expanding it won't work. Each individual keyword needs to be a separate node.
So if before it was:
```
parameters = Dict(dict={
       ' with_time_reversal': True
        'reference_distance': 0.02
}
seekpath_structure_analysis(structure, parameters
```
now it should be
```
seekpath_structure_analysis(structure, with_time_reversal=Bool(True), reference_distance=Float(0.02))
```

**Comment by hongyi-zhao** [comment]
I tested it with this [example](https://aiida-tutorials.readthedocs.io/en/latest/_downloads/41fc098a6347cd8d1653a71b79cc51eb/launch_auto-wannier_workflow.py) and it seems work.

But it you are right, the call method is more complex now, we should judge on the datatype of the keywords and then do the corresponding passing.

Regards

**Comment by qiaojunfeng** [comment]
I tested and it worked, because the `kpoints_distance_for_bands` in line 225 
https://github.com/aiidateam/aiida-wannier90-workflows/blob/725260ead5cbc7b7038aac7f3bf2155c813be114/aiida_wannier90_workflows/workflows/bands.py#L220-L226
is the one provided in the workflow inputs
https://github.com/aiidateam/aiida-wannier90-workflows/blob/725260ead5cbc7b7038aac7f3bf2155c813be114/aiida_wannier90_workflows/workflows/bands.py#L93-L98
which is always of type `orm.Float`, that's why it works.

A problem is line 222 where `self.ctx.protocol['kpoints_distance_for_bands']` is of type `float`, but this line won't be executed since some time ago I added a `default` to the `kpoints_distance_for_bands` in the `spec.input`. For safety reason, I wrap the `self.ctx.protocol['kpoints_distance_for_bands']` in `orm.Float` (see commit https://github.com/aiidateam/aiida-wannier90-workflows/commit/f90181871aadad40fbc267308e5ce1967e981063), though maybe this line should be removed in the future.

**Comment by hongyi-zhao** [comment]
I still not figure out why you use the most simplified seekpath parameters for that.  The seekpath package has many parameters for the dict defined in the following:

```
 seekpath_parameters = orm.Dict( 
     dict={'reference_distance': kpoints_distance_for_bands} 
 ) 
```

Why you only use one of them.

Regards

**Comment by qiaojunfeng** [comment]
> I still cannot figure out why you use the most simplified seekpath parameters for that. The seekpath package has many parameters for the dict defined by you:
> 
> ```
>  seekpath_parameters = orm.Dict( 
>      dict={'reference_distance': kpoints_distance_for_bands} 
>  ) 
> ```
> 
> But you only use one of them.
> 
> Regards

That's simply because `reference_distance` is used for calculating the band structure. I haven't met with problems of finding primitive cell by seekpath, so I just use the default parameters of seekpath.

**Pull request merged**
