### PR TITLE
Made options and settings customizable for every step of the workchain

### PR DESCRIPTION
**Pull request by Crivella**
Improved the customizability of the workchain, by allowing the user to specify custom `options` and `settings` for every step of the workchain:
Changes:

- The input port `options` has been modified to require a nested dictionary where the keys reflect the name of the workchain step (scf, nscf, projwfc, pw2wannier90, wannier90, bands) and the associated value is the `metadata.options` dictionary for that step. If the key is not present, the default value generated by `get_default_options` will be used.
- The input port `settings` has been added, with the same behaviour as `options`, where the keys reflect the name of the workchain step, and the values are the `settings` dictionary to be passed the associated workchain step. If the key is not present, no settings will not be passed (old behaviour)

### CODE REVIEW

**Comment by sphuber** [comment]
Note that this is exactly what I was referring to in my last group meeting. If the workchain were to use `expose_inputs` to expose the specs of the sub workflows and calculations, then a user could always specify custom options and settings and you won't need custom code for it in the workchain implementation. Maybe something to consider if you ever may want to refactor the process specification.

**Comment by Crivella** [comment]
@sphuber As far as I can see this is done at the level of the `Wannier90WorkChain` workchain. Doing so at the `Wannier90BandsWorkChain` would create a giant Dict node for the input. 

I think Junfeng is working on a solution with the input_generator, but I wanted to post this changes in case someone needs them in the meanwhile (I had to customize the options and settings in order to run on marconi100 with qe_gpu)

**Comment by qiaojunfeng** [comment]
> Note that this is exactly what I was referring to in my last group meeting. If the workchain were to use `expose_inputs` to expose the specs of the sub workflows and calculations, then a user could always specify custom options and settings and you won't need custom code for it in the workchain implementation. Maybe something to consider if you ever may want to refactor the process specification.

I already have a base `Wannier90WorkChain` which hardly modifies input parameters and exposes all the inputs of the sub workchain
https://github.com/aiidateam/aiida-wannier90-workflows/blob/3e8fbcfe4d14d562a4549eecf90b5356f4b73fc9/aiida_wannier90_workflows/workflows/wannier.py#L44-L47

However, that workchain is too basic and not easy to use, so there is a `Wannier90BandsWorkChain` which accepts several spec.input, generate all the parameters, easy to use but hard to customize the generated parameters.

So now I tend to move all the parameter generations to a `generate_input` function, again expose all the sub workchain in `Wannier90BandsWorkChain`. Hopefully, no need to add `spec.input` anymore.

Now here I have a question with `generate_input`: I need to run seekpath in the workchain, to get primitive cell, and some auto-generated params depend on number of atoms in the cell. If I run seekpath calcfunction in `generate_input`, it will mess up the database, I think `generate_input` should be a pure function without side-effects. Well if I auto-generate params for an arbitrary cell, it would be wrong for the workchain, if workchain ran a seekpath internally. One way to solve this is run a not-calcfunction version of seekpath function in `generate_input`, and generate params for primitive cell, pass params to workchain, workchain internally runs a calcfunction version of seekpath, and it should work. But this is still ugly, if the user passes a not-primitive cell, well `generate_input` returns params for a different cell, not very consistent. Another way is add a AssertionError if user pass a not-primitive cell, but this violates the principle of automatically running on all structures. Any thoughts about solving this dilemma? Thanks!

**Comment by sphuber** [comment]
Good to hear you are working on an inputs generator and separate the concerns of that and workchain logic. I also agree with you that the input generator should not change the database. If you need to run `calcfunctions` in the generator to determine certain inputs, make sure to pass `metadata={store_provenance: False}` which makes sure that nothing gets stored in the database.

Regarding the seekpath problem, as I see it, you have two options:
1) Require that all pre-generated inputs are fully self-consistent, and in this case that means you either have to refuse non-standardized structures, or just standardize them and accept that a different structure can be used for the workchain then the user passed to the inputs generator
2) Accept any structure and potentially pass inputs to top-level workchain that are not fully self-consisten, but you correct this in the workchain itself. This may make sense anyway if you rely on sub workchains (such as the `PwRelaxWorkChain`) which already may normalize the structure and so change the parameters that subsequent steps in your workchains should have to follow. Those subsequent steps should look at the results of preceding sub processes and adapt the inputs accordingly. The ultimate input parameters for those steps may not be exactly those that were put in on the top level workchain, but we do this all the time (for other legitimate reasons) and so I think this is perfectly fine.

I personally would lean to option 2. Without knowing exactly how your parameters depend on the structure, I feel it is perfectly fine to update certain parameters for sub processes based on results of preceding steps.

**Comment by qiaojunfeng** [comment]
> Good to hear you are working on an inputs generator and separate the concerns of that and workchain logic. I also agree with you that the input generator should not change the database. If you need to run `calcfunctions` in the generator to determine certain inputs, make sure to pass `metadata={store_provenance: False}` which makes sure that nothing gets stored in the database.
> 
> Regarding the seekpath problem, as I see it, you have two options:
> 
> 1. Require that all pre-generated inputs are fully self-consistent, and in this case that means you either have to refuse non-standardized structures, or just standardize them and accept that a different structure can be used for the workchain then the user passed to the inputs generator
> 2. Accept any structure and potentially pass inputs to top-level workchain that are not fully self-consisten, but you correct this in the workchain itself. This may make sense anyway if you rely on sub workchains (such as the `PwRelaxWorkChain`) which already may normalize the structure and so change the parameters that subsequent steps in your workchains should have to follow. Those subsequent steps should look at the results of preceding sub processes and adapt the inputs accordingly. The ultimate input parameters for those steps may not be exactly those that were put in on the top level workchain, but we do this all the time (for other legitimate reasons) and so I think this is perfectly fine.
> 
> I personally would lean to option 2. Without knowing exactly how your parameters depend on the structure, I feel it is perfectly fine to update certain parameters for sub processes based on results of preceding steps.

Thanks, Sebastiaan!

Based on the 2nd option, I just came up with another solution:
1. If the user calls `generate_inputs`, then it will generate params for that structure, whether the structure is standardized or not. This is legitimate because some times user wants to get wannier functions for a specific structure.
2. The workchain exposes all. If the user submit workchain with all the params, then the workchain will use those params. I agree modifying some of the params is unavoidable, as I already done this in the `Wannier90WorkChain`. But for the wannier workchains, the number of bands, number of wannier functions are the key params that I cannot just auto correct them in the workchain, they determine very much the quality of wannier functions, so user wants to tune them. While for num_bands of non-standardized cell vs. primitive cell, it indeed is wrong, needs to be corrected. But it's hard for code to differentiate it's an error that needs to be corrected, or it's explicitly required by the user.
3. So, what if the workchain could call `generate_inputs` internally? If no user-input params, the workchain first calls seekpath, then calls generate_inputs for the primitive cell, everything goes well
4. Even better, make the `generate_inputs` granular, so the workchain could accept partial input params, and auto-generate remaining params accordingly.

So in final, `generate_inputs` can work on both standardized and non-standardized cell, and return consistent params.
Workchain can accept every customized params, fill partial params, or auto-generate all the params.

The only unperfect thing is the `Wannier90BandsWorkChain`, since it requires standardized kpath for bands. If user passes a structure with params, there needs some check to ensure the structure is primitive. If there is only one structure but no params as input, then the workchain can run seekpath to standardize the structure, and do the following.

Seems this is a decent solution, for both automation and customization.

**Comment by sphuber** [comment]
I see your point about not automatically wanting to override key parameters, however, I don't see how having the workchain call `generate_inputs` internally will change this. Whether you call this once on the outside, or within the workchain, you will be overriding these parameters in both cases. Or am I missing something? If these parameters really *have* to correspond to the structure and they really *cannot* be adapted automatically by the workchain, then the workchain should simply make sure that the structure is never changed. That would be my conclusion

**Comment by qiaojunfeng** [comment]
> I see your point about not automatically wanting to override key parameters, however, I don't see how having the workchain call `generate_inputs` internally will change this. Whether you call this once on the outside, or within the workchain, you will be overriding these parameters in both cases. Or am I missing something? If these parameters really _have_ to correspond to the structure and they really _cannot_ be adapted automatically by the workchain, then the workchain should simply make sure that the structure is never changed. That would be my conclusion

If the workchain calls `generate_inputs` internally, then the user-input params could behave as the `override` parameter in the current QE `generate_inputs`: the user-input are "protected", and if `generate_inputs` finds any inconsistency, then raise an exception. Does this work?

**Pull request closed without merging**
